# Generated by Django 4.2.7 on 2025-12-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField()),
                ('skill_match_score', models.IntegerField(default=0)),
                ('experience_match_score', models.IntegerField(default=0)),
                ('education_match_score', models.IntegerField(default=0)),
                ('location_match_score', models.IntegerField(default=0)),
                ('matching_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('match_details', models.JSONField(blank=True, default=dict)),
                ('is_viewed_by_candidate', models.BooleanField(default=False)),
                ('is_viewed_by_recruiter', models.BooleanField(default=False)),
                ('is_favorited_by_candidate', models.BooleanField(default=False)),
                ('is_favorited_by_recruiter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.job')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-overall_score', '-created_at'],
            },
        ),
    ]
