# Generated by Django 4.2.7 on 2025-12-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='resumes.resume'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['-overall_score', '-created_at'], name='matches_overall_81b357_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['resume', '-overall_score'], name='matches_resume__d0b10c_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['job', '-overall_score'], name='matches_job_id_bc4335_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('resume', 'job')},
        ),
    ]
